# Base configuration for the KML to SVG converter
base_url: "https://cadastre.data.gouv.fr/data/etalab-cadastre/2025-04-01/geojson/departements"
file_template: "cadastre-{dep}-batiments.json.gz"

# OpenStreetMap settings
osm:
  overpass_url: "https://overpass-api.de/api/interpreter"
  timeout: 30
  cache_dir: "osm-cache"
  cache_file: "osmdata.json"

# SVG output settings
svg:
  width: 800
  height: 600
  padding: 0.05  # 5% padding
  
# Styling settings
styles:
  building:
    fill: "#E4E0D8"  # Light beige for buildings
    stroke: "#D4D0C8"
    stroke-width: 1
    opacity: 0.9
  
  road:
    primary:
      stroke: "#FCD68A"
      stroke-width: 5
      casing-color: "#F4BC6C"
      casing-width: 7
      opacity: 1
    secondary:
      stroke: "#FAFAFA"
      stroke-width: 4
      casing-color: "#E0E0E0"
      casing-width: 6
      opacity: 1
    path:
      stroke: "#FFFFFF"
      stroke-width: 2
      casing-color: "#E0E0E0"
      casing-width: 3
      opacity: 0.8
      
  landuse:
    allotment:
      fill: "#E8F4D9"
      stroke: "#76A32D"
      stroke-width: 2
      opacity: 0.9
    park:
      fill: "#90EE90"
      stroke: "#7BE37B"
      stroke-width: 1
      opacity: 0.7
    forest:
      fill: "#C6DFB3"
      stroke: "#B5CE9F"
      stroke-width: 1
      opacity: 0.6
